### PR TITLE
Add missing pages (privacy, returnpolicy, termsofuse)

### LINKED ISSUE #12: Create Terms and conditions page
Create Terms and conditions page

The page should contain be responsive and match the theme.

### PR DESCRIPTION
**Pull request by jsvigneshkanna**
#### Describe your changes

- Added 3 missing pages (Privacy, Return Policy, Terms of Use)
- The 3 pages are response in mobile devices with help of tailwindcss
- These are as standards to other pages
@NandanVyas 

#### Link to issue this resolves
#12 

#### Screenshot of changes(if relevant)
1. return policy- 
image
2. Privacy Policy- 
image
3. Terms and Condition-
image

- [x] The **title** should be something descriptive about what your changes do. _(It will default to whatever you put as your commit message.)_
- [x] This **description** should include ...
  - [x] A short summary of your changes
  - [x] A link to the issue that relates to these changes
  - [x] A screenshot of the changes if possible!
- [x] Add `NandanVyas` as a reviewer
- [x] Add yourself as assignee

### CODE REVIEW

**Comment by jsvigneshkanna** [comment]
Hi @NandanVyas ,

Please review the code, let me know if any changes required
Please add `hacktoberfest-accepted` label, so that I can keep track of all my Contributions this month

Appreciate that!

**Comment by jsvigneshkanna** [comment]
Hi @NandanVyas ,

Please check my code and let me know if any changes required

**Comment by NandanVyas** [comment]
@jsvigneshkanna The pages must have some styling and the dark mode should have a background of gray-900. You can see the other pages to get an idea about the theme that the bookstore is following.

If you need any help feel free to contact me.

**Review by NandanVyas — CHANGES_REQUESTED** [review]
- All the pages require some space in the x-axis.
- The return policy page consists of a single paragraph and is not very readable. Can you please make it a bit more readable?
- The privacy policy page is missing a heading. The content seems fine.
- Please ensure that you follow the respective patterns of styling for light mode and dark mode.

**Pull request closed without merging**
